export const COUNTRY_INFO: Record<string, { currency: string; dial: string }> = {
  "Afghanistan": { currency: "AFN", dial: "+93" },
  "Albania": { currency: "ALL", dial: "+355" },
  "Algeria": { currency: "DZD", dial: "+213" },
  "Andorra": { currency: "EUR", dial: "+376" },
  "Angola": { currency: "AOA", dial: "+244" },
  "Argentina": { currency: "ARS", dial: "+54" },
  "Armenia": { currency: "AMD", dial: "+374" },
  "Australia": { currency: "AUD", dial: "+61" },
  "Austria": { currency: "EUR", dial: "+43" },
  "Azerbaijan": { currency: "AZN", dial: "+994" },
  "Bahamas": { currency: "BSD", dial: "+1" },
  "Bahrain": { currency: "BHD", dial: "+973" },
  "Bangladesh": { currency: "BDT", dial: "+880" },
  "Barbados": { currency: "BBD", dial: "+1" },
  "Belarus": { currency: "BYN", dial: "+375" },
  "Belgium": { currency: "EUR", dial: "+32" },
  "Belize": { currency: "BZD", dial: "+501" },
  "Benin": { currency: "XOF", dial: "+229" },
  "Bhutan": { currency: "BTN", dial: "+975" },
  "Bolivia": { currency: "BOB", dial: "+591" },
  "Bosnia and Herzegovina": { currency: "BAM", dial: "+387" },
  "Botswana": { currency: "BWP", dial: "+267" },
  "Brazil": { currency: "BRL", dial: "+55" },
  "Brunei": { currency: "BND", dial: "+673" },
  "Bulgaria": { currency: "BGN", dial: "+359" },
  "Burkina Faso": { currency: "XOF", dial: "+226" },
  "Burundi": { currency: "BIF", dial: "+257" },
  "Cambodia": { currency: "KHR", dial: "+855" },
  "Cameroon": { currency: "XAF", dial: "+237" },
  "Canada": { currency: "CAD", dial: "+1" },
  "Cape Verde": { currency: "CVE", dial: "+238" },
  "Central African Republic": { currency: "XAF", dial: "+236" },
  "Chad": { currency: "XAF", dial: "+235" },
  "Chile": { currency: "CLP", dial: "+56" },
  "China": { currency: "CNY", dial: "+86" },
  "Colombia": { currency: "COP", dial: "+57" },
  "Comoros": { currency: "KMF", dial: "+269" },
  "Congo": { currency: "XAF", dial: "+242" },
  "Costa Rica": { currency: "CRC", dial: "+506" },
  "Croatia": { currency: "EUR", dial: "+385" },
  "Cuba": { currency: "CUP", dial: "+53" },
  "Cyprus": { currency: "EUR", dial: "+357" },
  "Czech Republic": { currency: "CZK", dial: "+420" },
  "Denmark": { currency: "DKK", dial: "+45" },
  "Djibouti": { currency: "DJF", dial: "+253" },
  "Dominica": { currency: "XCD", dial: "+1" },
  "Dominican Republic": { currency: "DOP", dial: "+1" },
  "Ecuador": { currency: "USD", dial: "+593" },
  "Egypt": { currency: "EGP", dial: "+20" },
  "El Salvador": { currency: "USD", dial: "+503" },
  "Equatorial Guinea": { currency: "XAF", dial: "+240" },
  "Eritrea": { currency: "ERN", dial: "+291" },
  "Estonia": { currency: "EUR", dial: "+372" },
  "Eswatini": { currency: "SZL", dial: "+268" },
  "Ethiopia": { currency: "ETB", dial: "+251" },
  "Fiji": { currency: "FJD", dial: "+679" },
  "Finland": { currency: "EUR", dial: "+358" },
  "France": { currency: "EUR", dial: "+33" },
  "Gabon": { currency: "XAF", dial: "+241" },
  "Gambia": { currency: "GMD", dial: "+220" },
  "Georgia": { currency: "GEL", dial: "+995" },
  "Germany": { currency: "EUR", dial: "+49" },
  "Ghana": { currency: "GHS", dial: "+233" },
  "Greece": { currency: "EUR", dial: "+30" },
  "Grenada": { currency: "XCD", dial: "+1" },
  "Guatemala": { currency: "GTQ", dial: "+502" },
  "Guinea": { currency: "GNF", dial: "+224" },
  "Guinea-Bissau": { currency: "XOF", dial: "+245" },
  "Guyana": { currency: "GYD", dial: "+592" },
  "Haiti": { currency: "HTG", dial: "+509" },
  "Honduras": { currency: "HNL", dial: "+504" },
  "Hungary": { currency: "HUF", dial: "+36" },
  "Iceland": { currency: "ISK", dial: "+354" },
  "India": { currency: "INR", dial: "+91" },
  "Indonesia": { currency: "IDR", dial: "+62" },
  "Iran": { currency: "IRR", dial: "+98" },
  "Iraq": { currency: "IQD", dial: "+964" },
  "Ireland": { currency: "EUR", dial: "+353" },
  "Israel": { currency: "ILS", dial: "+972" },
  "Italy": { currency: "EUR", dial: "+39" },
  "Ivory Coast": { currency: "XOF", dial: "+225" },
  "Jamaica": { currency: "JMD", dial: "+1" },
  "Japan": { currency: "JPY", dial: "+81" },
  "Jordan": { currency: "JOD", dial: "+962" },
  "Kazakhstan": { currency: "KZT", dial: "+7" },
  "Kenya": { currency: "KES", dial: "+254" },
  "Kiribati": { currency: "AUD", dial: "+686" },
  "Kuwait": { currency: "KWD", dial: "+965" },
  "Kyrgyzstan": { currency: "KGS", dial: "+996" },
  "Laos": { currency: "LAK", dial: "+856" },
  "Latvia": { currency: "EUR", dial: "+371" },
  "Lebanon": { currency: "LBP", dial: "+961" },
  "Lesotho": { currency: "LSL", dial: "+266" },
  "Liberia": { currency: "LRD", dial: "+231" },
  "Libya": { currency: "LYD", dial: "+218" },
  "Liechtenstein": { currency: "CHF", dial: "+423" },
  "Lithuania": { currency: "EUR", dial: "+370" },
  "Luxembourg": { currency: "EUR", dial: "+352" },
  "Madagascar": { currency: "MGA", dial: "+261" },
  "Malawi": { currency: "MWK", dial: "+265" },
  "Malaysia": { currency: "MYR", dial: "+60" },
  "Maldives": { currency: "MVR", dial: "+960" },
  "Mali": { currency: "XOF", dial: "+223" },
  "Malta": { currency: "EUR", dial: "+356" },
  "Mauritania": { currency: "MRU", dial: "+222" },
  "Mauritius": { currency: "MUR", dial: "+230" },
  "Mexico": { currency: "MXN", dial: "+52" },
  "Moldova": { currency: "MDL", dial: "+373" },
  "Monaco": { currency: "EUR", dial: "+377" },
  "Mongolia": { currency: "MNT", dial: "+976" },
  "Montenegro": { currency: "EUR", dial: "+382" },
  "Morocco": { currency: "MAD", dial: "+212" },
  "Mozambique": { currency: "MZN", dial: "+258" },
  "Myanmar": { currency: "MMK", dial: "+95" },
  "Namibia": { currency: "NAD", dial: "+264" },
  "Nauru": { currency: "AUD", dial: "+674" },
  "Nepal": { currency: "NPR", dial: "+977" },
  "Netherlands": { currency: "EUR", dial: "+31" },
  "New Zealand": { currency: "NZD", dial: "+64" },
  "Nicaragua": { currency: "NIO", dial: "+505" },
  "Niger": { currency: "XOF", dial: "+227" },
  "Nigeria": { currency: "NGN", dial: "+234" },
  "North Korea": { currency: "KPW", dial: "+850" },
  "North Macedonia": { currency: "MKD", dial: "+389" },
  "Norway": { currency: "NOK", dial: "+47" },
  "Oman": { currency: "OMR", dial: "+968" },
  "Pakistan": { currency: "PKR", dial: "+92" },
  "Palau": { currency: "USD", dial: "+680" },
  "Palestine": { currency: "ILS", dial: "+970" },
  "Panama": { currency: "PAB", dial: "+507" },
  "Papua New Guinea": { currency: "PGK", dial: "+675" },
  "Paraguay": { currency: "PYG", dial: "+595" },
  "Peru": { currency: "PEN", dial: "+51" },
  "Philippines": { currency: "PHP", dial: "+63" },
  "Poland": { currency: "PLN", dial: "+48" },
  "Portugal": { currency: "EUR", dial: "+351" },
  "Qatar": { currency: "QAR", dial: "+974" },
  "Romania": { currency: "RON", dial: "+40" },
  "Russia": { currency: "RUB", dial: "+7" },
  "Rwanda": { currency: "RWF", dial: "+250" },
  "Saint Kitts and Nevis": { currency: "XCD", dial: "+1" },
  "Saint Lucia": { currency: "XCD", dial: "+1" },
  "Saint Vincent and the Grenadines": { currency: "XCD", dial: "+1" },
  "Samoa": { currency: "WST", dial: "+685" },
  "San Marino": { currency: "EUR", dial: "+378" },
  "Saudi Arabia": { currency: "SAR", dial: "+966" },
  "Senegal": { currency: "XOF", dial: "+221" },
  "Serbia": { currency: "RSD", dial: "+381" },
  "Seychelles": { currency: "SCR", dial: "+248" },
  "Sierra Leone": { currency: "SLE", dial: "+232" },
  "Singapore": { currency: "SGD", dial: "+65" },
  "Slovakia": { currency: "EUR", dial: "+421" },
  "Slovenia": { currency: "EUR", dial: "+386" },
  "Solomon Islands": { currency: "SBD", dial: "+677" },
  "Somalia": { currency: "SOS", dial: "+252" },
  "South Africa": { currency: "ZAR", dial: "+27" },
  "South Korea": { currency: "KRW", dial: "+82" },
  "South Sudan": { currency: "SSP", dial: "+211" },
  "Spain": { currency: "EUR", dial: "+34" },
  "Sri Lanka": { currency: "LKR", dial: "+94" },
  "Sudan": { currency: "SDG", dial: "+249" },
  "Suriname": { currency: "SRD", dial: "+597" },
  "Sweden": { currency: "SEK", dial: "+46" },
  "Switzerland": { currency: "CHF", dial: "+41" },
  "Syria": { currency: "SYP", dial: "+963" },
  "Taiwan": { currency: "TWD", dial: "+886" },
  "Tajikistan": { currency: "TJS", dial: "+992" },
  "Tanzania": { currency: "TZS", dial: "+255" },
  "Thailand": { currency: "THB", dial: "+66" },
  "Timor-Leste": { currency: "USD", dial: "+670" },
  "Togo": { currency: "XOF", dial: "+228" },
  "Tonga": { currency: "TOP", dial: "+676" },
  "Trinidad and Tobago": { currency: "TTD", dial: "+1" },
  "Tunisia": { currency: "TND", dial: "+216" },
  "Turkey": { currency: "TRY", dial: "+90" },
  "Turkmenistan": { currency: "TMT", dial: "+993" },
  "Tuvalu": { currency: "AUD", dial: "+688" },
  "Uganda": { currency: "UGX", dial: "+256" },
  "Ukraine": { currency: "UAH", dial: "+380" },
  "United Arab Emirates": { currency: "AED", dial: "+971" },
  "United Kingdom": { currency: "GBP", dial: "+44" },
  "United States": { currency: "USD", dial: "+1" },
  "Uruguay": { currency: "UYU", dial: "+598" },
  "Uzbekistan": { currency: "UZS", dial: "+998" },
  "Vanuatu": { currency: "VUV", dial: "+678" },
  "Vatican City": { currency: "EUR", dial: "+379" },
  "Venezuela": { currency: "VES", dial: "+58" },
  "Vietnam": { currency: "VND", dial: "+84" },
  "Yemen": { currency: "YER", dial: "+967" },
  "Zambia": { currency: "ZMW", dial: "+260" },
  "Zimbabwe": { currency: "ZWL", dial: "+263" },
};