import { Tenant, TenantUser, ActivityEvent } from "./types";

import bcrypt from "bcryptjs";


export const SEED_TENANTS: Tenant[] = [
  {
    id: "clt_marina",
    name: "Marina Dry Cleaners",
    slug: "marina",
    contactName: "Ahmed Al-Farsi",
    email: "ahmed@marinadc.ae",
    phone: "+971 4 555 0111",
    country: "United Arab Emirates",
    currency: "AED",
    locale: "ar",
    plan: "enterprise",
    status: "active",
    createdAt: "2023-02-14",
    branches: 6,
    seatsUsed: 22,
    storageUsedMB: 41200,
    monthlyOrders: 8420,
    mrr: 349,
    featureOverrides: {},
  taxEnabled: false,
taxRate: 0,},
  {
    id: "clt_pressed",
    name: "Pressed & Fresh",
    slug: "pressedfresh",
    contactName: "Sarah Whitmore",
    email: "sarah@pressedfresh.co.uk",
    phone: "+44 20 7946 0102",
    country: "United Kingdom",
    currency: "GBP",
    locale: "en",
    plan: "professional",
    status: "active",
    createdAt: "2023-06-02",
    branches: 2,
    seatsUsed: 8,
    storageUsedMB: 6300,
    monthlyOrders: 2110,
    mrr: 129,
    featureOverrides: { whatsapp: true }, // paid add-on beyond their plan
  taxEnabled: false,
taxRate: 0,},
  {
    id: "clt_soapbox",
    name: "SoapBox Laundry",
    slug: "soapbox",
    contactName: "Diego Martins",
    email: "diego@soapbox.pt",
    phone: "+351 21 000 4400",
    country: "Portugal",
    currency: "EUR",
    locale: "en",
    plan: "professional",
    status: "active",
    createdAt: "2024-01-19",
    branches: 1,
    seatsUsed: 5,
    storageUsedMB: 2900,
    monthlyOrders: 1340,
    mrr: 129,
    featureOverrides: {},
  taxEnabled: false,
taxRate: 0,},
  {
    id: "clt_limpio",
    name: "Limpio Express",
    slug: "limpio",
    contactName: "Valentina Cruz",
    email: "valentina@limpio.mx",
    phone: "+52 55 1234 9000",
    country: "Mexico",
    currency: "MXN",
    locale: "en",
    plan: "starter",
    status: "active",
    createdAt: "2024-03-08",
    branches: 1,
    seatsUsed: 3,
    storageUsedMB: 640,
    monthlyOrders: 720,
    mrr: 49,
    featureOverrides: {},
  taxEnabled: false,
taxRate: 0,},
  {
    id: "clt_bluewave",
    name: "Blue Wave Cleaners",
    slug: "bluewave",
    contactName: "Kenji Tanaka",
    email: "kenji@bluewave.jp",
    phone: "+81 3 5555 2323",
    country: "Japan",
    currency: "JPY",
    locale: "en",
    plan: "starter",
    status: "trial",
    createdAt: "2026-06-20",
    trialEndsAt: "2026-07-11",
    branches: 1,
    seatsUsed: 2,
    storageUsedMB: 120,
    monthlyOrders: 96,
    mrr: 0,
   taxEnabled: false,
taxRate: 0,
featureOverrides: {},
  },
  {
    id: "clt_crown",
    name: "Crown Laundromat",
    slug: "crown",
    contactName: "Olivia Brooks",
    email: "olivia@crownlaundry.com",
    phone: "+1 415 555 7788",
    country: "United States",
    currency: "USD",
    locale: "en",
    plan: "enterprise",
    status: "active",
    createdAt: "2022-11-30",
    branches: 11,
    seatsUsed: 47,
    storageUsedMB: 88700,
    monthlyOrders: 15980,
    mrr: 349,
    featureOverrides: {},
  taxEnabled: false,
taxRate: 0,},
  {
    id: "clt_sparkle",
    name: "Sparkle Care",
    slug: "sparkle",
    contactName: "Fatima Noor",
    email: "fatima@sparklecare.qa",
    phone: "+974 4000 1212",
    country: "Qatar",
    currency: "QAR",
    locale: "ar",
    plan: "professional",
    status: "suspended",
    createdAt: "2023-09-11",
    branches: 3,
    seatsUsed: 12,
    storageUsedMB: 9100,
    monthlyOrders: 0,
    mrr: 129,
    featureOverrides: { arabic: true },
  taxEnabled: false,
taxRate: 0,},
  {
    id: "clt_freshfold",
    name: "FreshFold Co.",
    slug: "freshfold",
    contactName: "Liam O'Connor",
    email: "liam@freshfold.ie",
    phone: "+353 1 555 0199",
    country: "Ireland",
    currency: "EUR",
    locale: "en",
    plan: "starter",
    status: "trial",
    createdAt: "2026-06-28",
    trialEndsAt: "2026-07-19",
    branches: 1,
    seatsUsed: 1,
    storageUsedMB: 40,
    monthlyOrders: 22,
    mrr: 0,
  taxEnabled: false,
taxRate: 0,
featureOverrides: {},
  },
  {
    id: "clt_royalpress",
    name: "Royal Press",
    slug: "royalpress",
    contactName: "Mohammed Rashid",
    email: "m.rashid@royalpress.sa",
    phone: "+966 11 555 3400",
    country: "Saudi Arabia",
    currency: "SAR",
    locale: "ar",
    plan: "enterprise",
    status: "active",
    createdAt: "2023-04-25",
    branches: 8,
    seatsUsed: 31,
    storageUsedMB: 52300,
    monthlyOrders: 11250,
    mrr: 349,
    featureOverrides: {},
  taxEnabled: false,
taxRate: 0,},
  {
    id: "clt_cleanco",
    name: "CleanCo Suburban",
    slug: "cleanco",
    contactName: "Grace Miller",
    email: "grace@cleanco.au",
    phone: "+61 2 5550 8080",
    country: "Australia",
    currency: "AUD",
    locale: "en",
    plan: "professional",
    status: "churned",
    createdAt: "2022-08-17",
    branches: 2,
    seatsUsed: 0,
    storageUsedMB: 7400,
    monthlyOrders: 0,
    mrr: 0,
    featureOverrides: {},
  taxEnabled: false,
taxRate: 0,},
];

const ROLES: TenantUser["role"][] = ["Owner", "Admin", "Manager", "Cashier", "Driver"];
const DEPTS = ["Front Counter", "Operations", "Delivery", "Finance", "Management"];
const FIRST = ["Sam", "Lena", "Omar", "Priya", "Yusuf", "Mia", "Carlos", "Aisha", "Tom", "Nadia"];
const LAST = ["Reed", "Khan", "Silva", "Park", "Haddad", "Novak", "Ivanov", "Osei", "Chen", "Rossi"];

// Generate a deterministic set of users per tenant based on seatsUsed.
export function seedUsersFor(t: Tenant): TenantUser[] {
  const n = Math.max(1, Math.min(t.seatsUsed, 12));
  const users: TenantUser[] = [];
  for (let i = 0; i < n; i++) {
    const role: TenantUser["role"] = i === 0 ? "Owner" : ROLES[(i % (ROLES.length - 1)) + 1];
    const first = FIRST[(i + t.name.length) % FIRST.length];
    const last = LAST[(i * 3 + t.slug.length) % LAST.length];
    users.push({    id: `${t.id}_u${i + 1}`,
      tenantId: t.id,
      name: `${first} ${last}`,
      email: `${first.toLowerCase()}.${last.toLowerCase()}@${t.slug}.com`,
      role,
      department: DEPTS[i % DEPTS.length],
      status: t.status === "suspended" || t.status === "churned" ? "disabled" : i === n - 1 && t.status === "trial" ? "invited" : "active",
      lastActive: t.status === "active" ? "2026-07-02" : t.status === "trial" ? "2026-07-01" : "2026-05-14",
      username: `${first.toLowerCase()}.${last.toLowerCase()}`,
      passwordHash: "$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31S.",
      
moduleOverrides: {},
    });
  }
  return users;
}

export const SEED_ACTIVITY: ActivityEvent[] = [
  { id: "a1", tenantId: "clt_freshfold", tenantName: "FreshFold Co.", kind: "signup", message: "Started a Starter trial", at: "2026-06-28T09:12:00" },
  { id: "a2", tenantId: "clt_pressed", tenantName: "Pressed & Fresh", kind: "upgrade", message: "Enabled WhatsApp add-on", at: "2026-07-01T14:03:00" },
  { id: "a3", tenantId: "clt_sparkle", tenantName: "Sparkle Care", kind: "suspend", message: "Suspended — payment failed (2 attempts)", at: "2026-06-30T02:40:00" },
  { id: "a4", tenantId: "clt_crown", tenantName: "Crown Laundromat", kind: "payment", message: "Paid invoice INV-2041 ($349.00)", at: "2026-07-01T00:05:00" },
  { id: "a5", tenantId: "clt_bluewave", tenantName: "Blue Wave Cleaners", kind: "signup", message: "Started a Starter trial", at: "2026-06-20T11:47:00" },
  { id: "a6", tenantId: "clt_marina", tenantName: "Marina Dry Cleaners", kind: "invite", message: "Invited 2 new cashiers (Branch 6)", at: "2026-06-29T16:22:00" },
  { id: "a7", tenantId: "clt_cleanco", tenantName: "CleanCo Suburban", kind: "downgrade", message: "Churned — cancelled subscription", at: "2026-06-15T08:00:00" },
  { id: "a8", tenantId: "clt_royalpress", tenantName: "Royal Press", kind: "login", message: "Owner signed in from Riyadh", at: "2026-07-02T07:31:00" },
];
